import {
  ShieldCheck,
  Bug,
  Activity,
  Leaf,
  Cpu,
} from "lucide-react";

import ProgressBar from "./ProgressBar";

function ResultCard({ result }) {
  if (!result) {
    return (
      <div className="rounded-3xl bg-white p-8 shadow-lg">

        <h2 className="mb-6 text-2xl font-bold text-green-700">
          🤖 AI Analysis
        </h2>

        <div className="flex h-80 items-center justify-center rounded-2xl border-2 border-dashed border-gray-300">

          <div className="text-center">

            <Cpu
              size={70}
              className="mx-auto mb-4 text-gray-400"
            />

            <h3 className="text-xl font-bold text-gray-600">
              No Analysis Yet
            </h3>

            <p className="mt-2 text-gray-500">
              Upload a crop image to start AI detection.
            </p>

          </div>

        </div>

      </div>
    );
  }

  return (
    <div className="rounded-3xl bg-white p-8 shadow-lg">

      <div className="mb-6 flex items-center gap-3">

        <ShieldCheck
          size={32}
          className="text-green-600"
        />

        <div>

          <h2 className="text-2xl font-bold">
            AI Detection Result
          </h2>

          <p className="text-gray-500">
            Generated by AgriTwin AI
          </p>

        </div>

      </div>

      <div className="space-y-5">

        <div className="rounded-2xl bg-green-50 p-5">

          <div className="flex items-center gap-3">

            <Bug
              className="text-red-500"
              size={24}
            />

            <div>

              <p className="text-sm text-gray-500">
                Disease
              </p>

              <h3 className="text-2xl font-bold">
                {result.disease}
              </h3>

            </div>

          </div>

        </div>

        <ProgressBar value={result.confidence} />

        <div className="grid grid-cols-2 gap-4">

          <div className="rounded-2xl bg-blue-50 p-5">

            <Activity
              size={22}
              className="mb-2 text-blue-600"
            />

            <p className="text-sm text-gray-500">
              Severity
            </p>

            <h3 className="text-xl font-bold">
              {result.severity}
            </h3>

          </div>

          <div className="rounded-2xl bg-lime-50 p-5">

            <Leaf
              size={22}
              className="mb-2 text-green-600"
            />

            <p className="text-sm text-gray-500">
              Crop
            </p>

            <h3 className="text-xl font-bold">
              {result.crop}
            </h3>

          </div>

        </div>

        <div className="rounded-2xl border border-green-200 bg-green-50 p-5">

          <p className="text-sm text-gray-500">
            AI Model
          </p>

          <h3 className="text-xl font-bold text-green-700">
            Gemini Vision + CNN Ensemble
          </h3>

        </div>

      </div>

    </div>
  );
}

export default ResultCard;